# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-CopyRecord
version:      1.01
version_from: CopyRecord.pm
installdirs:  site
requires:
    DBI:                           1.4
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
